version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo "Install phase - start"

pre_build:
  commands:
    - echo "Pre-build phase - start"
    - cd backend
    - chmod +x gradlew

build:
  commands:
    - echo "Build backend"
    - cd backend
    - ./gradlew clean test build
    - cd ..

    - echo "Build frontend"
    - cd frontend
    - npm ci
    - npm run build
    - cd ..


  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - backend/build/libs/*.jar
    - frontend/dist/**/*
