version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo "Install phase - start"

  pre_build:
    commands:
      - echo "Pre-build phase - start"
      - chmod +x gradlew || true

  build:
    commands:
      - echo "Build backend (gradle at repo root)"
      - ./gradlew clean test build

      - echo "Build frontend"
      - cd frontend
      - npm ci
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - build/libs/*.jar
    - frontend/dist/**/*
    - appspec.yml
    - scripts/**/*
